steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/helpful-airway-447521-j4/aagam-100996581/app:${SHORT_SHA}',
      '-f', 'Assignment 2 Files/Dockerfile', 'Assignment 2 Files'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/helpful-airway-447521-j4/aagam-100996581/app:${SHORT_SHA}'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'assignment2-service',
      '--image', 'us-central1-docker.pkg.dev/helpful-airway-447521-j4/aagam-100996581/app:${SHORT_SHA}',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
